### PR TITLE
Add biopython to requirements.

### PR DESCRIPTION
**Pull request by roryk**
Hi ya'll,

Thanks for open sourcing this-- what license were you thinking about releasing it under. I added the missing biopython to the dependencies.

Thanks!

### CODE REVIEW

**Comment by marghoob** [comment]
Hi Rory,

Thanks for your interest in BreakSeq2. The license has been added to the repository. Currently, we are not using any biopython module, so I am not sure about the added dependency in your pull request-it would help if you can elaborate on that. 

Regards,
Marghoob.

**Comment by roryk** [comment]
Hi @marghoob,

Thanks for adding the license. Here is the line requiring biopython:

https://github.com/bioinform/breakseq2/blob/829320550a7ceeb927999a461b985f38b5fad8b3/breakseq2/biopy/io/Fasta.py#L3

**Comment by marghoob** [comment]
Thanks. That clears it for me.

**Comment by roryk** [comment]
Thanks @mrghoob!

**Pull request merged**
